general:
  configVersion: 5
  dropIfInventoryIsFull: true
  checkTicks: 3600 # 20 ticks in one second
  chatPrefix: IDL
integration:
  AuthMe: true
mysql:
  host: localhost
  port: 3306
  database: minecraft
  user: root
  password: 1234
  autoMigration: true
