name: ItemDatabaseLink # the plugins name as it should appear in the plugin list /pl
version: 1.2 # the plugin's version
author: Assada
main: idl.Main
api-version: 1.18 # the version of the API you want to use, required starting with 1.13
commands:
  get:
    description: Get all income items
    usage: /<command>
    permission: idl.command.get
softdepend: [AuthMe]
permissions:
  idl.*:
    description: Gives access to all commands
    children:
      idl.command.get: true
  idl.command.get:
    description: Access to get command and all ingame checks
    default: true